config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :categories do
    resources :expenses
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    user.admin? ? admin_abilities(user) : user_abilities(user)
  end

  private

  def admin_abilities(_user)
    can :manage, :all
  end

  def user_abilities(user)
    can :manage, User, id: user.id
    can :manage, Expense, author_id: user.id
    can :manage, Category, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_expenses
  has_many :expenses, through: :category_expenses

  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :icon, presence: true

  ICONS = [
    'fa-solid fa-utensils',
    'fa-solid fa-tshirt',
    'fa-solid fa-gas-pump',
    'fa-solid fa-shopping-cart',
    'fa-solid fa-credit-card',
    'fa-solid fa-bus',
    'fa-solid fa-subway',
    'fa-solid fa-train',
    'fa-solid fa-bolt',
    'fa-solid fa-water',
    'fa-solid fa-heartbeat',
    'fa-solid fa-gamepad',
    'fa-solid fa-question',
    'fa-solid fa-bowling-ball',
    'fa-solid fa-band-aid'
  ].freeze

  def total_expenses
    expenses.sum(:amount)
  end

  def category_expenses(current_user)
    expenses
      .where.not(name: "dummy-expense-#{current_user.id}")
      .order(created_at: :desc)
  end
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :expense
  belongs_to :category
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  has_many :category_expenses
  has_many :categories, through: :category_expenses

  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :amount,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0
            }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
  has_many :categories, -> { distinct }, through: :expenses

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }

  def admin?
    role == 'admin'
  end

  def user_categories
    categories.where.not(name: "dummy-categrory-#{id}")
  end

  # create a dummy category then create dummy expense with that category
  def dummy_data(user)
    category =
      Category.new(
        name: "dummy-categrory-#{user.id}",
        icon: 'fa-solid fa-utensils'
      )
    category.save
    expense =
      Expense.new(
        name: "dummy-expense-#{user.id}",
        amount: 0,
        author_id: user.id,
        category_ids: [category.id]
      )
    expense.save
  end

  # check if dummy category and dummy expense exist
  def dummy_data?(id)
    categories.find_by(name: "dummy-categrory-#{id}") &&
      expenses.find_by(name: "dummy-expense-#{id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.user_categories
  end

  def show
    @category = Category.find(params[:id])
    redirect_to category_expenses_path(@category)
  end

  def new
    @category = Category.new
  end

  def create
    current_user.dummy_data(current_user) unless current_user.dummy_data?(current_user.id)
    new_category = Category.new(category_params)
    if new_category.save
      current_user
        .expenses
        .find_by(name: "dummy-expense-#{current_user.id}")
        .categories << new_category
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[index new create]

  def index
    @expenses = @category.category_expenses(current_user)
  end

  def show
    @expense = Expense.find(params[:id])
  end

  def new
    @user_categories = current_user.user_categories
    @expense = Expense.new
  end

  def create
    expense = Expense.new(expense_params)
    expense.author_id = current_user.id

    if expense.save
      redirect_to category_expenses_path(@category),
                  notice: 'Expense was successfully created.'
    else
      render :new
    end
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_to_categories, if: -> { user_signed_in? }
  def index
    render 'home/index'
  end

  private

  def redirect_to_categories
    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li class="flex items-center py-2 px-4 border-b rounded-lg hover:bg-gray-100">
  <%= link_to category_path(category) do %>
    <i class="<%= category.icon %> p-4 mr-2"></i>
    <%= category.name %>
  <% end %>
</li>

app/views/categories/_form.html.erb
<%= form_with model: category, local: true do |form| %>
  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div class="mb-4">
    <%= form.label :icon, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.collection_select :icon, Category::ICONS, :itself, :itself do |icon| %>
      <%= content_tag(:i, nil, class: icon) %> <%= icon %>
    <% end %>
  </div>
  <div class="flex items-center justify-between">
    <%= form.submit "Create Category", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<section class="flex flex-col w-full max-w-lg bg-white shadow-md rounded-lg p-6">
  <ul class="pb-5">
    <% @categories.each do |category| %>
      <li class="flex items-center py-2 px-4 border-b rounded-lg hover:bg-gray-100">
        <%= link_to category_path(category), class: "w-full flex items-center" do %>
          <i class="<%= category.icon %> p-4 mr-2 w-1/4"></i>
          <%= content_tag :span, category.name, class: "w-2/4" %>
          <%= content_tag :span, category.total_expenses, class: "w-1/4 text-right" %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to "New Category", new_category_path, class: "bg-green-600 p-5 text-center text-white font-bold rounded-lg hover:bg-green-500" %>
</section>

app/views/categories/new.html.erb
<section>
  <h1 class="text-3xl font-bold mb-5">New Category</h1>
  <%= render "form", category: @category %>
</section>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: category_expenses_path(@category), local: true) do |form| %>
  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div class="mb-4">
    <%= form.label :amount, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :amount, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <%# add atleast one category %>
  <div class="mb-4">
    <%= form.label :category_id, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%# create a collection of check boxes of @user_categories and assign the category_ids to the expense. @category is checked already %>
    <%= form.collection_check_boxes :category_ids, @user_categories, :id, :name do |category| %>
      <%= category.label class: "mr-4" do %>
        <% if category.object.id == @category.id %>
          <%= category.check_box(checked: true, class: "mr-2") %>
        <% else %>
          <%= category.check_box(class: "mr-2") %>
        <% end %>
        <%= category.text %>
      <% end %>
    <% end %>
  </div>
  <div class="flex items-center justify-between">
    <%= form.submit "Create Expense", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<section class="flex flex-col w-full max-w-lg bg-white shadow-md rounded-lg p-6">
  <div class="flex items-center justify-between pb-5 text-3xl font-semibold w-full border-b">
    <%= @category.name %> Expenses
    -
    <%= number_to_currency(@category.total_expenses)%>
  </div>
  <ul>
    <% @expenses.each do |expense| %>
      <li class="flex items-center py-2 px-4 border-b rounded-lg hover:bg-gray-100">
        <%= link_to category_expense_path(@category, expense), class: "w-full flex items-center" do %>
          <i class="<%= @category.icon %> p-4 mr-2 w-1/4"></i>
          <%= content_tag :span, expense.name, class: "w-2/4" %>
          <%= content_tag :span, number_to_currency(expense.amount), class: "w-1/4 text-right" %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to "New Expense", new_category_expense_path(@category), class: "bg-green-600 p-5 text-center text-white font-bold rounded-lg hover:bg-green-500" %>
</section>

app/views/expenses/new.html.erb
<section class="flex flex-col w-full max-w-lg bg-white shadow-md rounded-lg p-6">
  <h1 class="text-3xl font-bold mb-5">New Expense</h1>
  <%= render "form", expense: @expense %>
  </section>

app/views/expenses/show.html.erb
<%# expense show page %>
<section class="flex flex-col w-full max-w-lg bg-white shadow-md rounded-lg p-6">
  <h1 class="text-3xl font-semibold pb-5">
    <%= @expense.name %>
  </h1>
  <ul class="pb-5">
    <li class="flex items-center py-2 px-4 border-b rounded-lg hover:bg-gray-100 gap-4">
      <strong>Amount:</strong>
      <%= number_to_currency(@expense.amount) %>
    </li>
    <li class="flex items-center py-2 px-4 border-b rounded-lg hover:bg-gray-100 gap-4">
      <strong>Categories:</strong>
      <%= @expense.categories.map(&:name).join(", ") %>
    </li>
  </ul>
</section>

app/views/home/index.html.erb
<section class="flex flex-col">
  <% if user_signed_in? %>
    <%= "categories" %>
  <% else %>
    <div class="flex flex-col h-screen relative">
      <h1 class="text-5xl font-bold my-auto"> Moolah Haven </h1>
      <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 w-full">
        <%= button_to "Log in", new_user_session_path, method: :get, class: "btn bg-blue-500 text-white w-full hover:bg-blue-600" %>
        <%= button_to "Sign up", new_user_registration_path, method: :get, class: "btn w-full hover:text-blue-500" %>
      </div>
    </div>
  <% end %>
</section>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <nav class="flex flex-col justify-between gap-6 bg-blue-600 text-white px-6 pt-4">
    <div class="flex items-center justify-between text-2xl font-bold">
      <% if current_page?(categories_path) %>
        <button id="hamburger-btn" class="nav-link-top" type="button">
          <i class="fa-solid fa-bars"></i>
        </button>
        <h2> Categories </h2>
        <i class="fa-solid fa-magnifying-glass"></i>

      <% elsif current_page?(new_category_path) || current_page?(category_expenses_path) %>
        <%= link_to('<i class="fa-solid fa-angle-left"></i>'.html_safe, categories_path) %>
        <h2> <%= "#{controller_name}" %> </h2>
        <i class="fa-solid fa-ellipsis-vertical"></i>

      <% elsif current_page?(new_category_expense_path) || current_page?(category_expense_path) %>
        <%= link_to('<i class="fa-solid fa-angle-left"></i>'.html_safe, category_expenses_path) %>
        <h2> <%= "#{controller_name}" %> </h2>
        <i class="fa-solid fa-ellipsis-vertical"></i>
      <% end %>
    </div>

    <div class="flex items-center justify-end gap-6">
      <% if user_signed_in? %>
        <%= link_to "Most Recent", "#", class: "nav-bottom hover:text-blue-500" %>
        <%= link_to "Most Ancient", "#", class: "nav-bottom hover:text-blue-500" %>
      <% end %>
    </div>

    <div id="popup" class="hidden absolute top-0 left-0 right-0 bottom-0 bg-blue-600 text-white px-6 py-4">
      <a href="#" class="text-3xl absolute top-0 right-0 mr-4 mt-2" id="close-popup-btn">
        <i class="fa-solid fa-times"></i>
      </a>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= button_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
<% else %>
  <% if !(controller_name == "home") %>
    <nav class="flex flex-col justify-between gap-6 bg-blue-600 text-white px-6 pt-4">
      <div class="flex items-center justify-between text-2xl font-bold">
        <% if controller_name == "registrations" %>
          <% title = "Sign up" %>
        <% elsif controller_name == "sessions" %>
          <% title = "Log in" %>
        <% else %>
          <% title = "#{controller_name}" %>
        <% end %>
        <%= link_to('<i class="fa-solid fa-angle-left"></i>'.html_safe, root_path) %>
        <h2> <%= title %> </h2>
        <i class="fa-solid fa-ellipsis-vertical"></i>
      </div>
    </nav>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen bg-gray-100" data-current-user="<%= current_user.to_json %>">
    <%= render "layouts/navigation" %>
    <div id="flash-messages">
      <p class="notice text-blue-600"><%= notice %></p>
      <p class="alert text-red-600"><%= alert %></p>
    </div>
    <main class="flex-1 flex flex-col items-center justify-center md:container md:mx-auto h-full">
      <%= yield %>
    </main>
  </body>
</html>